### ISSUE TITLE
Everything should be dynamic!

### ISSUE THREAD

**Issue by Foxboron** [mpolden/jarvis2#12]
I spent a few days with Jarvis and made a infoscreen for Creativia that ran through the course of The Gathering 2015. Pretty awesome project!

Few of the problems i had:

I essentially ripped out the calendar tiles and added something that read from an .ics file. The problem however was that nothing in the javascript was very dynamic. I had to manually write a little bit to make sure the text was enough for the tiles.
https://github.com/Foxboron/Frank/blob/master/app/static/widgets/creativiascene/creativiascene.js#L29

The project also does not handle different screen sizes very well in my experience. This could be PEBCAK and i'm just horrible with CSS and Javascript.

Result: http://pr0n.sesse.net/tg15/original/DSC_4278.JPG

Awesome project, might be using it again next year!

**Comment by martinp** [comment]
Glad you like it, and fun to see it used at TG.

If I understand you correctly you want the amount of content to be adjusted dynamically within the sizex/sizey values of the widget? I'm not sure that could be done without making assumptions about the content. I guess it could be done on a per-widget basis (e.g. for calendar).

**Comment by Foxboron** [comment]
Yes, exactly. Sleepy and not typing well :)

But trying to make this standardized somehow would be great.
